apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: multi-cluster-app

# Standard deploy config (used by custom actions)
deploy:
  helm:
    releases:
      - name: whereami
        chartPath: chart
        namespace: default
        setValueTemplates:
          clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"

profiles:
  - name: config
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: workspace/source/chart
            namespace: default
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
  - name: member
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: workspace/source/chart
            namespace: default
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"

# Custom actions for Cloud Deploy custom targets
# These run with deploy_parameters available as CLOUD_DEPLOY_* env vars
customActions:
  - name: render-helm
    containers:
      - name: render
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "=== All Environment Variables ==="
            env | sort
            echo "================================="
            echo ""
            echo "=== Current Working Directory ==="
            pwd
            echo "================================="
            echo ""
            echo "=== List Current Directory ==="
            ls -la .
            echo "==============================="
            echo ""
            echo "=== List /workspace ==="
            ls -la /workspace 2>/dev/null || echo "/workspace does not exist"
            echo "========================"
            echo ""
            echo "=== List /workspace/source ==="
            ls -la /workspace/source 2>/dev/null || echo "/workspace/source does not exist"
            echo "==============================="
            echo ""
            echo "=== List root / ==="
            ls -la /
            echo "==================="
  - name: deploy-gke
    containers:
      - name: deploy
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Deploying to cluster: ${CLOUD_DEPLOY_cluster_name} in ${CLOUD_DEPLOY_cluster_location}"
            gcloud container clusters get-credentials ${CLOUD_DEPLOY_cluster_name} \
              --zone=${CLOUD_DEPLOY_cluster_location} \
              --project=${CLOUD_DEPLOY_project}
            kubectl apply -f /workspace/input/manifest.yaml
