apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: multi-cluster-app

# Custom actions for Cloud Deploy custom targets
# Cloud Deploy requires separate render and deploy actions
# Deploy parameters are passed as environment variables (ClusterType, cluster_name, etc.)
customActions:
  - name: render-helm
    containers:
      - name: render
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "=== Render: ${ClusterType} ==="
            
            # Download source
            gsutil cp "${CLOUD_DEPLOY_INPUT_GCS_PATH}" /tmp/source.tgz
            mkdir -p /workspace/source && tar -xzf /tmp/source.tgz -C /workspace/source
            
            # Install helm
            curl -sL https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz | tar -xzC /tmp
            mv /tmp/linux-amd64/helm /usr/local/bin/helm
            
            # Render with helm template (no skaffold needed)
            mkdir -p /workspace/output
            helm template whereami /workspace/source/chart \
              --namespace default \
              --set clusterType="${ClusterType}" \
              > /workspace/output/manifest.yaml
            
            echo "=== Rendered Manifest ===" && cat /workspace/output/manifest.yaml && echo "========================="
            
            # Upload results
            gsutil cp /workspace/output/manifest.yaml "${CLOUD_DEPLOY_OUTPUT_GCS_PATH}/manifest.yaml"
            echo '{"resultStatus":"SUCCEEDED","manifestFile":"manifest.yaml"}' > /tmp/results.json
            gsutil cp /tmp/results.json "${CLOUD_DEPLOY_OUTPUT_GCS_PATH}/results.json"

  - name: deploy-gke
    containers:
      - name: deploy
        image: gcr.io/google.com/cloudsdktool/cloud-sdk
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "=== Deploy to ${cluster_name} ==="
            
            # Download manifest
            gsutil cp "${CLOUD_DEPLOY_INPUT_GCS_PATH}/manifest.yaml" /tmp/manifest.yaml
            
            # Get credentials and apply
            gcloud container clusters get-credentials ${cluster_name} \
              --zone=${cluster_location} --project=${project}
            kubectl apply -f /tmp/manifest.yaml
            
            # Upload results
            echo '{"resultStatus":"SUCCEEDED"}' > /tmp/results.json
            gsutil cp /tmp/results.json "${CLOUD_DEPLOY_OUTPUT_GCS_PATH}/results.json"
            echo "=== Deploy complete ==="
