apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: multi-cluster-app
deploy:
  helm:
    releases:
      - name: whereami
        chartPath: /workspace/source/chart
        namespace: default
        setValueTemplates:
          clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
profiles:
  - name: config
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
  - name: member
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
