apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: multi-cluster-app
deploy:
  helm:
    releases:
      - name: whereami
        chartPath: /workspace/source/chart
        namespace: default
        setValues:
          clusterType: "unknown"
profiles:
  - name: config
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            setValues:
              clusterType: "unknown"
  - name: member
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            setValues:
              clusterType: "unknown"
