apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: multi-cluster-app
deploy:
  helm:
    releases:
      - name: whereami
        chartPath: /workspace/source/chart
        namespace: default
        # Cloud Deploy passes deployParameters via --set flag directly to Helm
        # No setValueTemplates needed - the --set="clusterType=config" is automatic
profiles:
  - name: config
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default

  - name: member
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
