apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: multi-cluster-app

# Standard deploy config (used by custom actions)
deploy:
  helm:
    releases:
      - name: whereami
        chartPath: chart
        namespace: default
        setValueTemplates:
          clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"

profiles:
  - name: config
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
  - name: member
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"

# Custom actions for Cloud Deploy custom targets
# These run with deploy_parameters available as CLOUD_DEPLOY_* env vars
customActions:
  - name: render-helm
    containers:
      - name: render
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "=== Deploy Parameters ==="
            echo "ClusterType: ${ClusterType}"
            echo "profile: ${profile}"
            echo "========================="
            
            # Download source from GCS
            echo "Downloading source from: ${CLOUD_DEPLOY_INPUT_GCS_PATH}"
            mkdir -p /workspace/source
            gsutil cp "${CLOUD_DEPLOY_INPUT_GCS_PATH}" /tmp/source.tgz
            tar -xzf /tmp/source.tgz -C /workspace/source
            
            echo "=== Source contents ==="
            ls -la /workspace/source/
            echo "======================="
            
            # Install skaffold
            echo "Installing skaffold..."
            curl -sLo /usr/local/bin/skaffold https://storage.googleapis.com/skaffold/releases/v2.16.1/skaffold-linux-amd64
            chmod +x /usr/local/bin/skaffold
            
            # Install helm (direct download - more reliable than get-helm-3 script)
            echo "Installing helm..."
            curl -sLo /tmp/helm.tar.gz https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz
            tar -xzf /tmp/helm.tar.gz -C /tmp
            mv /tmp/linux-amd64/helm /usr/local/bin/helm
            chmod +x /usr/local/bin/helm
            echo "Helm version: $(helm version --short)"
            
            # Export deploy parameters as environment variables
            export CLOUD_DEPLOY_ClusterType="${ClusterType}"
            export CLOUD_DEPLOY_profile="${profile}"
            
            # Render
            mkdir -p /workspace/output
            echo "Running skaffold render with profile: ${profile}"
            echo "CLOUD_DEPLOY_ClusterType=${CLOUD_DEPLOY_ClusterType}"
            skaffold render \
              --filename=/workspace/source/skaffold.yaml \
              --profile=${profile} \
              --output=/workspace/output/manifest.yaml \
              --offline=true \
              --digest-source=none \
              --set clusterType="${CLOUD_DEPLOY_ClusterType}"
            
            echo "=== Rendered Manifest ==="
            cat /workspace/output/manifest.yaml
            echo "========================="
            
            # Upload results to GCS (required for custom targets)
            echo "Uploading results to: ${CLOUD_DEPLOY_OUTPUT_GCS_PATH}"
            gsutil cp /workspace/output/manifest.yaml "${CLOUD_DEPLOY_OUTPUT_GCS_PATH}/manifest.yaml"
            
            # Create and upload results.json
            cat > /tmp/results.json << EOF
            {
              "resultStatus": "SUCCEEDED",
              "manifestFile": "${CLOUD_DEPLOY_OUTPUT_GCS_PATH}/manifest.yaml"
            }
            EOF
            gsutil cp /tmp/results.json "${CLOUD_DEPLOY_OUTPUT_GCS_PATH}/results.json"
            
            echo "Render complete!"
  - name: deploy-gke
    containers:
      - name: deploy
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "=== Deploy Parameters ==="
            echo "cluster_name: ${cluster_name}"
            echo "cluster_location: ${cluster_location}"
            echo "project: ${project}"
            echo "========================="
            
            # Download manifest from GCS (from render output)
            # CLOUD_DEPLOY_INPUT_GCS_PATH points to the render output directory
            echo "Downloading manifest from: ${CLOUD_DEPLOY_INPUT_GCS_PATH}/manifest.yaml"
            mkdir -p /workspace/input
            gsutil cp "${CLOUD_DEPLOY_INPUT_GCS_PATH}/manifest.yaml" /workspace/input/manifest.yaml
            
            echo "=== Manifest to deploy ==="
            cat /workspace/input/manifest.yaml
            echo "=========================="
            
            # Get cluster credentials
            echo "Getting cluster credentials..."
            gcloud container clusters get-credentials ${cluster_name} \
              --zone=${cluster_location} \
              --project=${project}
            
            # Apply
            echo "Applying manifests..."
            kubectl apply -f /workspace/input/manifest.yaml
            
            # Upload results.json
            echo "Uploading results..."
            cat > /tmp/results.json << EOF
            {
              "resultStatus": "SUCCEEDED"
            }
            EOF
            gsutil cp /tmp/results.json "${CLOUD_DEPLOY_OUTPUT_GCS_PATH}/results.json"
            
            echo "Deploy complete!"
