apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: multi-cluster-app
deploy:
  helm:
    releases:
      - name: whereami
        chartPath: /workspace/source/chart
        namespace: default
        setValueTemplates:
          clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
profiles:
  # Profile for config cluster
  - name: config
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            # Read ClusterType from Cloud Deploy's deployParameters (not hardcoded)
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
  # Profile for member cluster
  - name: member
    deploy:
      helm:
        releases:
          - name: whereami
            chartPath: /workspace/source/chart
            namespace: default
            # Read ClusterType from Cloud Deploy's deployParameters (not hardcoded)
            setValueTemplates:
              clusterType: "{{.CLOUD_DEPLOY_ClusterType}}"
